version: '3.1'

services:

  sme_postgres:
    image: postgres
    restart: always
    container_name: "sme-db"
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
      TZ: "Asia/Bangkok"
    networks:
      - odoo_network 

  sme_odoo_12:
    depends_on:
      - kaotul_postgres
    image: "odoo:12.0"
    restart: always
    container_name: "sme-odoo-12"
    environment:
      TZ: "Asia/Bangkok"
      HOST: "sme-db"
      USER: "odoo"
      PASSWORD: "P@ssw0rd"
    volumes:
      - ./config/12:/etc/odoo
      - odoo12_data:/var/lib/odoo
      - odoo12_addons:/mnt/extra-addons
    ports:
      - 8012:8069
    networks:
      - odoo_network 
        
  sme_pgadmin:
    depends_on:
      - sme_postgres
    image: "dpage/pgadmin4"
    container_name: "sme-pgadmin"
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      PGADMIN_DEFAULT_EMAIL: "kaotul@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd" 
    ports:
      - 8080:80
    networks:
      - odoo_network 

volumes:
  odoo12_data:
  odoo12_addons:

networks:
  odoo_network:
    driver: bridge
    ipam: 
      config:
      - subnet:   172.32.0.0/24
